### get tenant-a hello1
GET https://test.example.com/hello1
Accept: application/json

### get tenant-a hellob
GET http://{{tenant-a-addr}}/hello2
Accept: application/json

### get tenant-b hello1
GET http://{{tenant-b-addr}}/hello1
Accept: application/json

### get tenant-b hellob
GET http://{{tenant-b-addr}}/hello2
Accept: application/json


### vhost_http_port代理测试
GET http://www.example-a.com:8080/hello1
Accept: application/json

### vhost_http_port代理测试
GET http://www.example-b.com:8080/hello1
Accept: application/json